version: 3

tasks:
  generate:
    aliases:
      - gen
    desc: "Gen code from proto file"
    cmds:
      - protoc -I proto ./proto/swap/swap.proto --go_out gen/go/ --go_opt=paths=source_relative --go-grpc_out=gen/go/ --go-grpc_opt=paths=source_relative
      - protoc -I proto ./proto/transfer/transfer.proto --go_out gen/go/ --go_opt=paths=source_relative --go-grpc_out=gen/go/ --go-grpc_opt=paths=source_relative